image: atlassian/default-image:2

pipelines:
  branches:
    develop:
      - step:
          name: Build & Test Server
          caches:
            - gradle
          script:
            - cd server
            - chmod +x gradlew
            - ./gradlew build

      - step:
          name: Restore npm packages
          caches:
            - node
          script:
            - writeFile -f next-lock.cache -d "$BITBUCKET_COMMIT"
            - npm ci

      - step:
          name: Build Client
          caches:
            - node
          script:
            - writeFile -f next-lock.cache -d "$BITBUCKET_COMMIT"
            - npm run build

      - step:
          name: Build & Publish Docker Images
          script:
            - docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
            - docker build -t avvduong/alphabeta.client:develop ./client
            - docker build -t avvduong/alphabeta.server:develop ./server
            - docker push avvduong/alphabeta.client:develop
            - docker push avvduong/alphabeta.server:develop

      - step:
          name: Deploy to Development Server
          deployment: development
          script:
            - pipe: atlassian/scp-deploy:0.3.10
              variables:
                USER: $SSH_USERNAME
                SERVER: $SSH_HOST
                REMOTE_PATH: "/home/alphabeta"
                LOCAL_PATH: "./docker-compose.yaml"
            - sshpass -p $SSH_PASSWORD ssh -o StrictHostKeyChecking=no $SSH_USERNAME@$SSH_HOST 'docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD'
            - sshpass -p $SSH_PASSWORD ssh -o StrictHostKeyChecking=no $SSH_USERNAME@$SSH_HOST 'docker compose --project-name alphabeta --profile develop up -d --pull=always'
            - sshpass -p $SSH_PASSWORD ssh -o StrictHostKeyChecking=no $SSH_USERNAME@$SSH_HOST 'docker logout'

    main:
      - step:
          name: Build & Test Server
          caches:
            - gradle
          script:
            - cd server
            - chmod +x gradlew
            - ./gradlew build

      - step:
          name: Restore npm packages
          caches:
            - node
          script:
            - writeFile -f next-lock.cache -d "$BITBUCKET_COMMIT"
            - npm ci

      - step:
          name: Build Client
          caches:
            - node
          script:
            - writeFile -f next-lock.cache -d "$BITBUCKET_COMMIT"
            - npm run build

      - step:
          name: Build & Publish Docker Images
          script:
            - docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
            - docker build -t avvduong/alphabeta.client:main ./client
            - docker build -t avvduong/alphabeta.server:main ./server
            - docker push avvduong/alphabeta.client:main
            - docker push avvduong/alphabeta.server:main

      - step:
          name: Deploy to Production Server
          deployment: production
          script:
            - pipe: atlassian/scp-deploy:0.3.10
              variables:
                USER: $SSH_USERNAME
                SERVER: $SSH_HOST
                REMOTE_PATH: "/home/alphabeta"
                LOCAL_PATH: "./docker-compose.yaml"
            - sshpass -p $SSH_PASSWORD ssh -o StrictHostKeyChecking=no $SSH_USERNAME@$SSH_HOST 'docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD'
            - sshpass -p $SSH_PASSWORD ssh -o StrictHostKeyChecking=no $SSH_USERNAME@$SSH_HOST 'docker compose --project-name alphabeta --profile production up -d --pull=always'
            - sshpass -p $SSH_PASSWORD ssh -o StrictHostKeyChecking=no $SSH_USERNAME@$SSH_HOST 'docker logout'

definitions:
  caches:
    gradle: ~/.gradle
    node: ~/.npm
